<?php

# ISO
$pays_iso = array(
  'AF' => 'Afghanistan',
  'ZA' => 'Afrique du Sud',
  'AL' => 'Albanie',
  'DZ' => 'Algérie',
  'DE' => 'Allemagne',
  'AD' => 'Andorre',
  'AO' => 'Angola',
  'AI' => 'Anguilla',
  'AQ' => 'Antarctique',
  'AG' => 'Antigua-et-Barbuda',
  'AN' => 'Antilles néerlandaises',
  'SA' => 'Arabie saoudite',
  'AR' => 'Argentine',
  'AM' => 'Arménie',
  'AW' => 'Aruba',
  'AU' => 'Australie',
  'AT' => 'Autriche',
  'AZ' => 'Azerbaïdjan',
  'BS' => 'Bahamas',
  'BH' => 'Bahreïn',
  'BD' => 'Bangladesh',
  'BB' => 'Barbade',
  'BE' => 'Belgique',
  'BZ' => 'Belize',
  'BM' => 'Bermudes',
  'BT' => 'Bhoutan',
  'BO' => 'Bolivie',
  'BA' => 'Bosnie-Herzégovine',
  'BW' => 'Botswana',
  'BN' => 'Brunéi Darussalam',
  'BR' => 'Brésil',
  'BG' => 'Bulgarie',
  'BF' => 'Burkina Faso',
  'BI' => 'Burundi',
  'BY' => 'Bélarus',
  'BJ' => 'Bénin',
  'KH' => 'Cambodge',
  'CM' => 'Cameroun',
  'CA' => 'Canada',
  'CV' => 'Cap-Vert',
  'CL' => 'Chili',
  'CN' => 'Chine',
  'CY' => 'Chypre',
  'CO' => 'Colombie',
  'KM' => 'Comores',
  'CG' => 'Congo',
  'KP' => 'Corée du Nord',
  'KR' => 'Corée du Sud',
  'CR' => 'Costa Rica',
  'HR' => 'Croatie',
  'CU' => 'Cuba',
  'CI' => 'Côte d’Ivoire',
  'DK' => 'Danemark',
  'DJ' => 'Djibouti',
  'DM' => 'Dominique',
  'EG' => 'Égypte',
  'AE' => 'Émirats arabes unis',
  'EC' => 'Équateur',
  'ER' => 'Érythrée',
  'ES' => 'Espagne',
  'EE' => 'Estonie',
  'VA' => 'État de la Cité du Vatican',
  'FM' => 'États fédérés de Micronésie',
  'US' => 'États-Unis',
  'ET' => 'Éthiopie',
  'SV' => 'El Salvador',
  'FJ' => 'Fidji',
  'FI' => 'Finlande',
  'FR' => 'France',
  'GA' => 'Gabon',
  'GM' => 'Gambie',
  'GH' => 'Ghana',
  'GI' => 'Gibraltar',
  'GD' => 'Grenade',
  'GL' => 'Groenland',
  'GR' => 'Grèce',
  'GP' => 'Guadeloupe',
  'GU' => 'Guam',
  'GT' => 'Guatemala',
  'GG' => 'Guernesey',
  'GN' => 'Guinée',
  'GQ' => 'Guinée équatoriale',
  'GW' => 'Guinée-Bissau',
  'GY' => 'Guyana',
  'GF' => 'Guyane française',
  'GE' => 'Géorgie',
  'GS' => 'Géorgie du Sud et les îles Sandwich du Sud',
  'HT' => 'Haïti',
  'HN' => 'Honduras',
  'HU' => 'Hongrie',
  'BV' => 'Île Bouvet',
  'CX' => 'Île Christmas',
  'NF' => 'Île Norfolk',
  'IM' => 'Île de Man',
  'KY' => 'Îles Caïmans',
  'CC' => 'Îles Cocos - Keeling',
  'CK' => 'Îles Cook',
  'FO' => 'Îles Féroé',
  'HM' => 'Îles Heard et MacDonald',
  'FK' => 'Îles Malouines',
  'MP' => 'Îles Mariannes du Nord',
  'MH' => 'Îles Marshall',
  'UM' => 'Îles Mineures Éloignées des États-Unis',
  'SB' => 'Îles Salomon',
  'TC' => 'Îles Turks et Caïques',
  'VG' => 'Îles Vierges britanniques',
  'VI' => 'Îles Vierges des États-Unis',
  'AX' => 'Îles Åland',
  'IN' => 'Inde',
  'ID' => 'Indonésie',
  'IQ' => 'Irak',
  'IR' => 'Iran',
  'IE' => 'Irlande',
  'IS' => 'Islande',
  'IL' => 'Israël',
  'IT' => 'Italie',
  'JM' => 'Jamaïque',
  'JP' => 'Japon',
  'JE' => 'Jersey',
  'JO' => 'Jordanie',
  'KZ' => 'Kazakhstan',
  'KE' => 'Kenya',
  'KG' => 'Kirghizistan',
  'KI' => 'Kiribati',
  'KW' => 'Koweït',
  'LA' => 'Laos',
  'LS' => 'Lesotho',
  'LV' => 'Lettonie',
  'LB' => 'Liban',
  'LY' => 'Libye',
  'LR' => 'Libéria',
  'LI' => 'Liechtenstein',
  'LT' => 'Lituanie',
  'LU' => 'Luxembourg',
  'MK' => 'Macédoine',
  'MG' => 'Madagascar',
  'MY' => 'Malaisie',
  'MW' => 'Malawi',
  'MV' => 'Maldives',
  'ML' => 'Mali',
  'MT' => 'Malte',
  'MA' => 'Maroc',
  'MQ' => 'Martinique',
  'MU' => 'Maurice',
  'MR' => 'Mauritanie',
  'YT' => 'Mayotte',
  'MX' => 'Mexique',
  'MD' => 'Moldavie',
  'MC' => 'Monaco',
  'MN' => 'Mongolie',
  'MS' => 'Montserrat',
  'ME' => 'Monténégro',
  'MZ' => 'Mozambique',
  'MM' => 'Myanmar',
  'NA' => 'Namibie',
  'NR' => 'Nauru',
  'NI' => 'Nicaragua',
  'NE' => 'Niger',
  'NG' => 'Nigéria',
  'NU' => 'Niue',
  'NO' => 'Norvège',
  'NC' => 'Nouvelle-Calédonie',
  'NZ' => 'Nouvelle-Zélande',
  'NP' => 'Népal',
  'OM' => 'Oman',
  'UG' => 'Ouganda',
  'UZ' => 'Ouzbékistan',
  'PK' => 'Pakistan',
  'PW' => 'Palaos',
  'PA' => 'Panama',
  'PG' => 'Papouasie-Nouvelle-Guinée',
  'PY' => 'Paraguay',
  'NL' => 'Pays-Bas',
  'PH' => 'Philippines',
  'PN' => 'Pitcairn',
  'PL' => 'Pologne',
  'PF' => 'Polynésie française',
  'PR' => 'Porto Rico',
  'PT' => 'Portugal',
  'PE' => 'Pérou',
  'QA' => 'Qatar',
  'HK' => 'R.A.S. chinoise de Hong Kong',
  'MO' => 'R.A.S. chinoise de Macao',
  'RO' => 'Roumanie',
  'GB' => 'Royaume-Uni',
  'RU' => 'Russie',
  'RW' => 'Rwanda',
  'CF' => 'République centrafricaine',
  'DO' => 'République dominicaine',
  'CD' => 'République démocratique du Congo',
  'CZ' => 'République tchèque',
  'RE' => 'Réunion',
  'EH' => 'Sahara occidental',
  'BL' => 'Saint-Barthélémy',
  'KN' => 'Saint-Kitts-et-Nevis',
  'SM' => 'Saint-Marin',
  'MF' => 'Saint-Martin',
  'PM' => 'Saint-Pierre-et-Miquelon',
  'VC' => 'Saint-Vincent-et-les Grenadines',
  'SH' => 'Sainte-Hélène',
  'LC' => 'Sainte-Lucie',
  'WS' => 'Samoa',
  'AS' => 'Samoa américaines',
  'ST' => 'Sao Tomé-et-Principe',
  'RS' => 'Serbie',
  'CS' => 'Serbie-et-Monténégro',
  'SC' => 'Seychelles',
  'SL' => 'Sierra Leone',
  'SG' => 'Singapour',
  'SK' => 'Slovaquie',
  'SI' => 'Slovénie',
  'SO' => 'Somalie',
  'SD' => 'Soudan',
  'LK' => 'Sri Lanka',
  'CH' => 'Suisse',
  'SR' => 'Suriname',
  'SE' => 'Suède',
  'SJ' => 'Svalbard et Île Jan Mayen',
  'SZ' => 'Swaziland',
  'SY' => 'Syrie',
  'SN' => 'Sénégal',
  'TJ' => 'Tadjikistan',
  'TZ' => 'Tanzanie',
  'TW' => 'Taïwan',
  'TD' => 'Tchad',
  'TF' => 'Terres australes françaises',
  'IO' => 'Territoire britannique de l\'océan Indien',
  'PS' => 'Territoire palestinien',
  'TH' => 'Thaïlande',
  'TL' => 'Timor oriental',
  'TG' => 'Togo',
  'TK' => 'Tokelau',
  'TO' => 'Tonga',
  'TT' => 'Trinité-et-Tobago',
  'TN' => 'Tunisie',
  'TM' => 'Turkménistan',
  'TR' => 'Turquie',
  'TV' => 'Tuvalu',
  'UA' => 'Ukraine',
  'UY' => 'Uruguay',
  'VU' => 'Vanuatu',
  'VE' => 'Venezuela',
  'VN' => 'Viêt Nam',
  'WF' => 'Wallis-et-Futuna',
  'YE' => 'Yémen',
  'ZM' => 'Zambie',
  'ZW' => 'Zimbabwe',
  'ZZ' => 'région indéterminée',
);
 
 
 
# NUMBER

$pays_num = array(
  '1' => 'Afghanistan'
  '2' => 'Afrique du Sud'
  '3' => 'Albanie'
  '4' => 'Algérie'
  '5' => 'Allemagne'
  '6' => 'Andorre'
  '7' => 'Angola'
  '8' => 'Anguilla'
  '9' => 'Antarctique'
  '10' => 'Antigua-et-Barbuda'
  '11' => 'Antilles néerlandaises'
  '12' => 'Arabie saoudite'
  '13' => 'Argentine'
  '14' => 'Arménie'
  '15' => 'Aruba'
  '16' => 'Australie'
  '17' => 'Autriche'
  '18' => 'Azerbaïdjan'
  '19' => 'Bahamas'
  '20' => 'Bahreïn'
  '21' => 'Bangladesh'
  '22' => 'Barbade'
  '23' => 'Belgique'
  '24' => 'Belize'
  '25' => 'Bermudes'
  '26' => 'Bhoutan'
  '27' => 'Bolivie'
  '28' => 'Bosnie-Herzégovine'
  '29' => 'Botswana'
  '30' => 'Brunéi Darussalam'
  '31' => 'Brésil'
  '32' => 'Bulgarie'
  '33' => 'Burkina Faso'
  '34' => 'Burundi'
  '35' => 'Bélarus'
  '36' => 'Bénin'
  '37' => 'Cambodge'
  '38' => 'Cameroun'
  '39' => 'Canada'
  '40' => 'Cap-Vert'
  '41' => 'Chili'
  '42' => 'Chine'
  '43' => 'Chypre'
  '44' => 'Colombie'
  '45' => 'Comores'
  '46' => 'Congo'
  '47' => 'Corée du Nord'
  '48' => 'Corée du Sud'
  '49' => 'Costa Rica'
  '50' => 'Croatie'
  '51' => 'Cuba'
  '52' => 'Côte d’Ivoire'
  '53' => 'Danemark'
  '54' => 'Djibouti'
  '55' => 'Dominique'
  '56' => 'Égypte'
  '57' => 'Émirats arabes unis'
  '58' => 'Équateur'
  '59' => 'Érythrée'
  '60' => 'Espagne'
  '61' => 'Estonie'
  '62' => 'État de la Cité du Vatican'
  '63' => 'États fédérés de Micronésie'
  '64' => 'États-Unis'
  '65' => 'Éthiopie'
  '66' => 'El Salvador'
  '67' => 'Fidji'
  '68' => 'Finlande'
  '69' => 'France'
  '70' => 'Gabon'
  '71' => 'Gambie'
  '72' => 'Ghana'
  '73' => 'Gibraltar'
  '74' => 'Grenade'
  '75' => 'Groenland'
  '76' => 'Grèce'
  '77' => 'Guadeloupe'
  '78' => 'Guam'
  '79' => 'Guatemala'
  '80' => 'Guernesey'
  '81' => 'Guinée'
  '82' => 'Guinée équatoriale'
  '83' => 'Guinée-Bissau'
  '84' => 'Guyana'
  '85' => 'Guyane française'
  '86' => 'Géorgie'
  '87' => 'Géorgie du Sud et les îles Sandwich du Sud'
  '88' => 'Haïti'
  '89' => 'Honduras'
  '90' => 'Hongrie'
  '91' => 'Île Bouvet'
  '92' => 'Île Christmas'
  '93' => 'Île Norfolk'
  '94' => 'Île de Man'
  '95' => 'Îles Caïmans'
  '96' => 'Îles Cocos - Keeling'
  '97' => 'Îles Cook'
  '98' => 'Îles Féroé'
  '99' => 'Îles Heard et MacDonald'
  '100' => 'Îles Malouines'
  '101' => 'Îles Mariannes du Nord'
  '102' => 'Îles Marshall'
  '103' => 'Îles Mineures Éloignées des États-Unis'
  '104' => 'Îles Salomon'
  '105' => 'Îles Turks et Caïques'
  '106' => 'Îles Vierges britanniques'
  '107' => 'Îles Vierges des États-Unis'
  '108' => 'Îles Åland'
  '109' => 'Inde'
  '110' => 'Indonésie'
  '111' => 'Irak'
  '112' => 'Iran'
  '113' => 'Irlande'
  '114' => 'Islande'
  '115' => 'Israël'
  '116' => 'Italie'
  '117' => 'Jamaïque'
  '118' => 'Japon'
  '119' => 'Jersey'
  '120' => 'Jordanie'
  '121' => 'Kazakhstan'
  '122' => 'Kenya'
  '123' => 'Kirghizistan'
  '124' => 'Kiribati'
  '125' => 'Koweït'
  '126' => 'Laos'
  '127' => 'Lesotho'
  '128' => 'Lettonie'
  '129' => 'Liban'
  '130' => 'Libye'
  '131' => 'Libéria'
  '132' => 'Liechtenstein'
  '133' => 'Lituanie'
  '134' => 'Luxembourg'
  '135' => 'Macédoine'
  '136' => 'Madagascar'
  '137' => 'Malaisie'
  '138' => 'Malawi'
  '139' => 'Maldives'
  '140' => 'Mali'
  '141' => 'Malte'
  '142' => 'Maroc'
  '143' => 'Martinique'
  '144' => 'Maurice'
  '145' => 'Mauritanie'
  '146' => 'Mayotte'
  '147' => 'Mexique'
  '148' => 'Moldavie'
  '149' => 'Monaco'
  '150' => 'Mongolie'
  '151' => 'Montserrat'
  '152' => 'Monténégro'
  '153' => 'Mozambique'
  '154' => 'Myanmar'
  '155' => 'Namibie'
  '156' => 'Nauru'
  '157' => 'Nicaragua'
  '158' => 'Niger'
  '159' => 'Nigéria'
  '160' => 'Niue'
  '161' => 'Norvège'
  '162' => 'Nouvelle-Calédonie'
  '163' => 'Nouvelle-Zélande'
  '164' => 'Népal'
  '165' => 'Oman'
  '166' => 'Ouganda'
  '167' => 'Ouzbékistan'
  '168' => 'Pakistan'
  '169' => 'Palaos'
  '170' => 'Panama'
  '171' => 'Papouasie-Nouvelle-Guinée'
  '172' => 'Paraguay'
  '173' => 'Pays-Bas'
  '174' => 'Philippines'
  '175' => 'Pitcairn'
  '176' => 'Pologne'
  '177' => 'Polynésie française'
  '178' => 'Porto Rico'
  '179' => 'Portugal'
  '180' => 'Pérou'
  '181' => 'Qatar'
  '182' => 'R.A.S. chinoise de Hong Kong'
  '183' => 'R.A.S. chinoise de Macao'
  '184' => 'Roumanie'
  '185' => 'Royaume-Uni'
  '186' => 'Russie'
  '187' => 'Rwanda'
  '188' => 'République centrafricaine'
  '189' => 'République dominicaine'
  '190' => 'République démocratique du Congo'
  '191' => 'République tchèque'
  '192' => 'Réunion'
  '193' => 'Sahara occidental'
  '194' => 'Saint-Barthélémy'
  '195' => 'Saint-Kitts-et-Nevis'
  '196' => 'Saint-Marin'
  '197' => 'Saint-Martin'
  '198' => 'Saint-Pierre-et-Miquelon'
  '199' => 'Saint-Vincent-et-les Grenadines'
  '200' => 'Sainte-Hélène'
  '201' => 'Sainte-Lucie'
  '202' => 'Samoa'
  '203' => 'Samoa américaines'
  '204' => 'Sao Tomé-et-Principe'
  '205' => 'Serbie'
  '206' => 'Serbie-et-Monténégro'
  '207' => 'Seychelles'
  '208' => 'Sierra Leone'
  '209' => 'Singapour'
  '210' => 'Slovaquie'
  '211' => 'Slovénie'
  '212' => 'Somalie'
  '213' => 'Soudan'
  '214' => 'Sri Lanka'
  '215' => 'Suisse'
  '216' => 'Suriname'
  '217' => 'Suède'
  '218' => 'Svalbard et Île Jan Mayen'
  '219' => 'Swaziland'
  '220' => 'Syrie'
  '221' => 'Sénégal'
  '222' => 'Tadjikistan'
  '223' => 'Tanzanie'
  '224' => 'Taïwan'
  '225' => 'Tchad'
  '226' => 'Terres australes françaises'
  '227' => 'Territoire britannique de l\'océan Indien'
  '228' => 'Territoire palestinien'
  '229' => 'Thaïlande'
  '230' => 'Timor oriental'
  '231' => 'Togo'
  '232' => 'Tokelau'
  '233' => 'Tonga'
  '234' => 'Trinité-et-Tobago'
  '235' => 'Tunisie'
  '236' => 'Turkménistan'
  '237' => 'Turquie'
  '238' => 'Tuvalu'
  '239' => 'Ukraine'
  '240' => 'Uruguay'
  '241' => 'Vanuatu'
  '242' => 'Venezuela'
  '243' => 'Viêt Nam'
  '244' => 'Wallis-et-Futuna'
  '245' => 'Yémen'
  '246' => 'Zambie'
  '247' => 'Zimbabwe'
  '248' => 'région indéterminée'
);

<?
